name: ci

on:
  pull_request:
    branches: [master]

env:
  FLUTTER_VERSION: "3.0.0"

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: flutter format . && git diff --exit-code

  analyze:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter analyze .

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter test --coverage
    - run: bash <(curl -s https://codecov.io/bash)

  android-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter build apk

  linux-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ninja-build libgtk-3-dev
    - run: ./tools/prepare
    - run: flutter build linux

  ios-build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter build ios --no-codesign

  macos-build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter build macos

  web-build:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare-web
    - run: flutter build web

  windows-build:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
    - run: ./tools/prepare
    - run: flutter build windows

  webtox:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build webtox image
        uses: docker/build-push-action@v2
